// import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function Home() {
  return (
    <>
      <header>
        <h1>Music is a Uinversal Language</h1>
        <nav></nav>
        <Link href="/">Home</Link>
        <Link href="/">MusicPost</Link>
      </header>
      <main>
        <section>
          <img src="" alt="" width={300} height={200} />
          <article>
            <p>
              Music therapy is the evidence-based practice of working with a
              person musically to achieve developmental, psychological,
              physical, emotional, or spiritual goal
            </p>
          </article>
        </section>
        <section>
          <img src="" alt="" width={300} height={200} />
          <article>
            <p>
              Music ineffability transports us away from the mundane, allays
              sadness, evokes laughter, brings us to tears and rallies us to
              stand in unison. It confronts our fears and aspirations.
            </p>
          </article>
        </section>
        <section>
          <img src="" alt="" width={300} height={200} />
          <article>
            <p>
              I have learned more about the way of the world, other people, and,
              I’ve gained a better understanding of myself through music than
              any other form of education.
            </p>
          </article>
        </section>
      </main>
      <footer>
        <p>Made by Themba &copy; 2024</p>
      </footer>
    </>
  );
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>MUSIC IS A UNIVERSAL LANGUAGE!</h1>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/add-favMusic">Add favMusic</Link>
        </nav>
        {header}
        {children}
        {footer}
        <footer>Made by Themba </footer>
      </body>
    </html>
  );
}
