import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  let header = (
    <header>
      <Link href={"/"}>
        <h1>Music is a Uinversal Language</h1>
      </Link>
    </header>
  );

  let footer = (
    <footer>
      <p>Made by Themba &copy 2024</p>
    </footer>
  );
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>MUSIC IS A UNIVERSAL LANGUAGE!</h1>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/add-favMusic">Add favMusic</Link>
        </nav>
        {header}
        {children}
        {footer}
      </body>
      <footer>Made by Themba </footer>
    </html>
  );
}
